apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: sa-app
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
          env:
            - name: discovery.type
              value: "single-node"
            - name: ES_JAVA_OPTS
              value: "-Xms128m -Xmx128m"
            - name: ELASTIC_USERNAME
              value: "elastic"
            - name: ELASTIC_PASSWORD
              value: "changeme"
            - name: xpack.security.enabled
              value: "false"   # 👈 Esto desactiva la seguridad
            - name: xpack.security.transport.ssl.enabled
              value: "false"   # 👈 Esto desactiva el SSL en el transporte interno
          ports:
            - containerPort: 9200
              name: http
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elasticsearch-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: sa-app
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
      name: http
