apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: sa-app
data:
  logstash.conf: |
    input {
      tcp {
        port => 5044
        codec => json
      }
    }

    filter {
      json {
        source => "message"
      }
      mutate {
        add_field => { "[@metadata][index]" => "%{service}-logs" }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch.sa-app.svc.cluster.local:9200"]
        index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
        user => "elastic"
        password => "changeme"
      }
      stdout { codec => rubydebug }
    }
