apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: sa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.5.0
          ports:
            - containerPort: 5044
            - containerPort: 9600
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: sa-app
spec:
  selector:
    app: logstash
  ports:
    - port: 5044
      targetPort: 5044
      name: logstash
    - port: 9600
      targetPort: 9600
      name: monitoring
