apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jorigot/swap:v1
          ports:
            - containerPort: 80
          env:
            - name: authServerUrl
              value: http://auth-service:3001
            - name: productServerUrl
              value: http://product-service:3002

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sa-app
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
