apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-order-pv
  namespace: sa-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:  # ✅ Compatible con Minikube/local
    path: /mnt/data/mysql-order

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-order-pvc
  namespace: sa-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-order
  namespace: sa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-order
  template:
    metadata:
      labels:
        app: mysql-order
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
            - name: MYSQL_DATABASE
              value: "order_db"
            - name: TZ
              value: "America/Guatemala"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-order-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-order-data
          persistentVolumeClaim:
            claimName: mysql-order-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: db-order
  namespace: sa-app
spec:
  type: NodePort  # expone puerto para carga de scripts o conexiones locales
  selector:
    app: mysql-order
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30309   # Usa este puerto, o uno libre entre 30000–32767
