apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-product-pv
  namespace: sa-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:                        # ✅ Compatible con Minikube/local
    path: /mnt/data/mysql-product

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-product-pvc
  namespace: sa-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-product
  namespace: sa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-product
  template:
    metadata:
      labels:
        app: mysql-product
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
            - name: MYSQL_DATABASE
              value: "product_db"
            - name: TZ
              value: "America/Guatemala"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-product-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-product-data
          persistentVolumeClaim:
            claimName: mysql-product-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: db-product
  namespace: sa-app
spec:
  type: NodePort               # ✅ expone puerto para scripts o conexiones externas
  selector:
    app: mysql-product
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30308          # Puedes cambiar este si está ocupado (rango: 30000–32767)
