apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-auth-pvc
  namespace: sa-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo  # ✅ importante para GKE Autopilot

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-auth
  namespace: sa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-auth
  template:
    metadata:
      labels:
        app: mysql-auth
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
            - name: MYSQL_DATABASE
              value: "auth_db"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-auth-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: mysql-auth-data
          persistentVolumeClaim:
            claimName: mysql-auth-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: db-userauth
  namespace: sa-app
spec:
  type: ClusterIP
  selector:
    app: mysql-auth
  ports:
    - port: 3306
      targetPort: 3306
