const router = require("express").Router();
const colaborador = require("./colaborador/colaborador");
const cliente = require("./cliente/cliente");
const admin = require("./admin/admin");
const auth = require("./auth/auth");
const categoria_producto = require("./categoria_producto/CategoriaProducto");
const cliente_oferta = require("./cliente_oferta/ClienteOferta");
const detalle_pedido = require("./detalle_pedido/DetallePedido");
const detalle_tarjeta = require("./detalle_tarjeta/DetalleTarjeta");
const egreso = require("./egreso/Egreso");
const estado_civil = require("./estado_civil/EstadoCivil");
const estado_existencia = require("./estado_existencia/EstadoExistencia");
const estado_oferta = require("./estado_oferta/EstadoOferta");
const estado_pedido = require("./estado_pedido/EstadoPedido");
const estado_usuario = require("./estado_usuario/EstadoUsuario");
const existencia = require("./existencia/Existencia");
const ingreso = require("./ingreso/Ingreso");
const ingreso_mercaderia = require("./ingreso_mercaderia/IngresoMercaderia");
const metodo_pago = require("./metodo_pago/MetodoPago");
const oferta = require("./oferta/Oferta");
const pago = require("./pago/Pago");
const pedido = require("./pedido/Pedido");
const producto = require("./producto/Producto");
const proveedor = require("./proveedor/Proveedor");
const retroalimentacion_producto = require("./retroalimentacion_producto/RetroalimentacionProducto");
const tipos_metodo_pago = require("./tipo_metodo_pago/TipoMetodoPago");
const tipo_usuario = require("./tipo_usuario/TipoUsuario");
const validacion_pago = require("./validacion_pago/ValidacionPago");
const valoracion_pagina = require("./valoracion_pagina/ValoracionPagina");
const lista_deseos = require("./lista_deseos/ListaDeseos");
const carrito = require("./carrito/carrito");
const reports = require("./reports/Reports");
router.use("/colaborador", colaborador);
router.use("/cliente", cliente);
router.use("/admin", admin);
router.use("/auth", auth);
router.use("/categoria_producto", categoria_producto);
router.use("/cliente_oferta", cliente_oferta);
router.use("/detalle_pedido", detalle_pedido);
router.use("/detalle_tarjeta", detalle_tarjeta);
router.use("/egreso", egreso);
router.use("/estado_civil", estado_civil);
router.use("/estado_existencia", estado_existencia);
router.use("/estado_oferta", estado_oferta);
router.use("/estado_pedido", estado_pedido);
router.use("/estado_usuario", estado_usuario);
router.use("/existencia", existencia);
router.use("/ingreso", ingreso);
router.use("/ingreso_mercaderia", ingreso_mercaderia);
router.use("/metodo_pago", metodo_pago);
router.use("/oferta", oferta);
router.use("/pago", pago);
router.use("/pedido", pedido);
router.use("/producto", producto);
router.use("/proveedor", proveedor);
router.use("/retroalimentacion_producto", retroalimentacion_producto);
router.use("/tipos_metodo_pago", tipos_metodo_pago);
router.use("/tipo_usuario", tipo_usuario);
router.use("/validacion_pago", validacion_pago);
router.use("/valoracion_pagina", valoracion_pagina);
router.use("/lista_deseos", lista_deseos);
router.use("/carrito", carrito);
router.use("/reports", reports);

module.exports = router;
