apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: sa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: order-service
          image: jpanaza/order-service:6
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
            - name: CORS_ORIGIN
              value: "http://34.71.88.73"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:3001"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:3002"
            - name: DB_HOST
              value: "db-order"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "1234"
            - name: DB_DATABASE
              value: "order_db"
          resources:                # ✅ Control de CPU/Memoria agregado
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: sa-app
spec:
  selector:
    app: order-service
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
