# Imagen base
FROM node:20-alpine

# Establecer directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar dependencias
COPY package*.json ./

# Instalar solo producción si es build final
RUN npm install --production

# Copiar el resto del código
COPY . .

# Exponer el puerto (ajústalo al que usas en .env)
EXPOSE 3003

# Comando por defecto
CMD ["node", "index.js"]

# Generar imagen
# docker build -t order-service .