name: CI/CD Pipeline - Proyecto SA

on:
  push:
    branches:
      - develop
      - feature/**

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Loguearse en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push auth-service
        run: |
          docker build -t jpanaza/auth-service:latest ./backends/auth-service
          docker push jpanaza/auth-service:latest

      - name: Build & Push product-service
        run: |
          docker build -t jpanaza/product-service:latest ./backends/product-service
          docker push jpanaza/product-service:latest

      - name: Build & Push order-service
        run: |
          docker build -t jpanaza/order-service:latest ./backends/order-service
          docker push jpanaza/order-service:latest

  test:
    name: Test Docker Containers
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Pull Images de DockerHub
        run: |
          docker pull jpanaza/auth-service:latest
          docker pull jpanaza/product-service:latest
          docker pull jpanaza/order-service:latest

      - name: Probar auth-service
        run: |
          docker run --rm --detach --name auth-service-test jpanaza/auth-service:latest && sleep 10 && docker stop auth-service-test

      - name: Probar product-service
        run: |
          docker run --rm --detach --name product-service-test jpanaza/product-service:latest && sleep 10 && docker stop product-service-test

      - name: Probar order-service
        run: |
          docker run --rm --detach --name order-service-test jpanaza/order-service:latest && sleep 10 && docker stop order-service-test
